- name: Install terminal and font packages
  ansible.builtin.apt:
    name:
      - fonts-symbola
      - fonts-noto-color-emoji
      - fonts-croscore
      - alacritty
      - foot
      - foot-themes
    state: present
  become: true

- name: Install term brew packages
  community.general.homebrew:
    name:
      - neovim
      - zellij
      - helix
    state: present

- name: Copy .icons
  ansible.builtin.copy:
    src: ".icons"
    dest: "~/.icons"

- name: Copy alacritty configuration
  ansible.builtin.copy:
    src: "alacritty.yml"
    dest: "~/.alacritty.yml"

- name: Copy zellij configuration
  ansible.builtin.copy:
    src: "config.kdl"
    dest: "~/.config/zellij/config.kdl"

- name: Copy foot terminal configuration
  ansible.builtin.copy:
    src: "foot.ini"
    dest: "~/.config/foot/foot.ini"

- name: Copy neovim configuration
  ansible.builtin.copy:
    src: "nvim/"
    dest: "~/.config/nvim/"

- name: Copy helix configuration
  ansible.builtin.copy:
    src: "helix/"
    dest: "~/.config/helix/"

- name: Install Cousine Nerd Font
  ansible.builtin.copy:
    src: "Cousine/"
    dest: "~/.local/share/fonts/Cousine/"

