- name: Install gui packages
  ansible.builtin.apt:
    name:
      - volumeicon-alsa
      - pavucontrol
      - rofi
      - lxappearance
      - arandr
      - xclip
      - maim
      - light
      - acpi
      - lm-sensors
      - zim-tools
      - kiwix-tools
      - kiwix
      - feh
      - mupdf
      - pass
      - pcmanfm
      - sxiv
      - nitrogen
    state: present
    update_cache: true
  become: true

- ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: u+x,g+x,o+x
  become: true
  with_fileglob:
    - "moz_*"

- name: Copy rofi configuration
  ansible.builtin.copy:
    src: "rofi/"
    dest: "~/.config/rofi/"

- name: Add user to video group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: video
    append: true
  become: true
