#!/usr/bin/env bash
ff="rofi -matching fuzzy -p pass -dmenu"
if [ -t 1 ] ; then ff="fzf"; fi

find ~/.password-store/snip -type f -iname '*.gpg' \
  | sed 's|/home/moz/.password-store/snip/||g' \
  | sed 's|.gpg||g' \
  | $ff \
  | sed 's|^|snip/|' \
  | xargs -r pass show | wl-copy
