#!/bin/sh

case "$(echo " Shutdown\n Reboot\n Logout\n鈴 Sleep\n Lock\n BM_Battery\n𢡄 BM_Balanced\n BM_Performance\n" | \
    wofi --dmenu -i -p "Power:")" in
        " Shutdown") exec systemctl poweroff;;
        " Reboot") exec systemctl reboot;;
        " Logout") exec sudo pkill sway;;
        "鈴 Sleep") exec systemctl suspend;;
        " Lock") exec swaylock -c "303030" -e;;
        " BM_Battery") exec system76-power profile battery && notify-send 'BM: Battery';;
        "𢡄 BM_Balanced") exec system76-power profile balanced && notify-send 'BM: Balanced';;
        " BM_Performance") exec system76-power profile performance && notify-send 'BM: Performance';;
esac
