#!/usr/bin/env bash
ff="rofi -matching fuzzy -p pass -dmenu"
if [ -t 1 ] ; then ff="fzf"; fi

find ~/.password-store/pass -type f -iname '*.gpg' \
  | sed 's|/home/moz/.password-store/pass/||g' \
  | sed 's|.gpg||g' \
  | $ff \
  | sed 's|^|pass/|' \
  | xargs -r pass show \
  | head -n1 | tr -d '\r' | wl-copy
