# Editor Config
theme = "catppuccin_mocha"

[editor]
true-color = true
bufferline = "always"
auto-pairs = true

[editor.file-picker]
hidden = true

[editor.statusline]
left = [ "mode", "file-name", "separator", "spacer", "diagnostics", ]
center = []
right = [
  "position", "separator",  "spacer", "position-percentage", "spacer", "separator", 
  "total-line-numbers", "separator",  "file-line-ending", "separator",  "file-type", ]
separator = "\uE0B3"
mode.normal = "NORMAL"
mode.select = "SELECT"
mode.insert = "INSERT"

[editor.cursor-shape]
insert= "bar"

[editor.lsp]
display-messages  = true
auto-signature-help  = true
display-signature-help-docs = true

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 0

[keys.normal]
# Undoing the 'd' + motion commands restores the selection which is annoying
u = ["undo", "collapse_selection"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "normal_mode"]

[keys.select]

# Some extra binds to allow us to insert/append in select mode because it's nice with multiple cursors
C-a = ["append_mode", "collapse_selection"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

