
- name: Install sway and related packages
  ansible.builtin.apt:
    name:
      - i3
      - i3blocks
      - i3lock-fancy
      - xss-lock
      - sway
      - swaybg
      - swayidle
      - swaylock
      - swaykbdd
      - xwayland
      - wireplumber
      - xdg-desktop-portal-wlr
      - wofi
      - wlr-randr
      - grim
      - grimshot
      - wdisplays
    state: present
  become: true

- name: Copy i3 config directory
  copy:
    src: "sway/"
    dest: "~/.config/i3/"

- name: Copy sway config directory
  copy:
    src: "sway/"
    dest: "~/.config/sway/"

- name: Copy i3blocks config directory
  copy:
    src: "i3blocks"
    dest: "~/.config/i3blocks/"
