
- name: Install sway and related packages
  ansible.builtin.apt:
    name:
      - i3
      - i3blocks
      - i3lock-fancy
      - xss-lock
      - sway
      - swaybg
      - swayidle
      - swaylock
      - xwayland
      - wireplumber
      - xdg-desktop-portal-wlr
      - wofi
      - wlr-randr
      - grim
      - grimshot
      - wdisplays
      - mako-notifier
      - waybar
    state: present
  become: true

- name: Copy sway config directory
  copy:
    src: "sway/"
    dest: "~/.config/sway/"

- name: Copy wofi config directory
  copy:
    src: "wofi/"
    dest: "~/.config/wofi/"

- name: Copy waybar config directory
  copy:
    src: "waybar/"
    dest: "~/.config/waybar/"

- name: Copy i3 config directory
  copy:
    src: "sway/"
    dest: "~/.config/i3/"

- name: Copy i3blocks config directory
  copy:
    src: "i3blocks/"
    dest: "~/.config/i3blocks/"

