- name: Install required packages on Ubuntu
  apt:
    name:
      - python-is-python3
      - python3-pip
      - python3-venv
      - lua5.1
    state: present
  become: true

- name: Activate virtual environment and install Python packages
  ansible.builtin.pip:
    name:
      - pandas
      - pyspark
      - litecli
      - duckdb
      - ipython
      - datasette
      - sqlite-utils
      - tqdm
      - polars
      - bpython
      - black
      - isort
      - jupyterlab
      - jupyterlab-lsp
      - jupyterlab-git
      - jupyterlab_code_formatter
      - jupyter-collaboration
      - jupyter_scheduler
      - catppuccin-jupyterlab
      - jedi-language-server
    virtualenv: "~/.moz_py/"
    virtualenv_command: "python3 -m venv"

- name: Install brew dependecies
  community.general.homebrew:
    name:
      - duckdb
      - pyright
      - marksman
      - awscli
      - kubectl
    state: present

- name: Copy example development files for python
  ansible.builtin.copy:
    src: "dev.py"
    dest: "~/.moz_py/dev.py"

- name: Copy example development files for sqlite
  ansible.builtin.copy:
    src: "dev.sqlite"
    dest: "~/.moz_py/dev.sqlite"

