- name: Install required packages on Ubuntu
  apt:
    name:
      - python-is-python3
      - python3-pip
      - python3-venv
      - lua5.1
      - openjdk-8-jdk
    state: present
  become: true
# - name: Set up Python virtual environment
#   command: python3 -m venv ~/.moz_py/
#   # args:
#   #   chdir: 

- name: Activate virtual environment and install Python packages
  ansible.builtin.pip:
    name:
      - pandas
      - pyspark
      - litecli
      - duckdb
      - ipython
      - datasette
      - sqlite-utils
      - tqdm
      - polars
      - bpython
    virtualenv: "~/.moz_py/"
    virtualenv_command: "python3 -m venv"

- name: Install brew dependecies
  community.general.homebrew:
    name:
      - duckdb
      - pyright
      - marksman
      - awscli
      - kubectl
    state: present

